@startuml
'The user couldn't complete the transaction

User -> GUI: Buy Ticket
GUI -> Database: Check for available seats
Database --> GUI: Error message
GUI --> User: No available seats
Database -> GUI: go to payment-GUI
GUI -> User: Ask for Card information
User -> GUI: Gives card information
GUI -> TicketControl: Verify price
TicketControl -> Authentication: Verify card information
Authentication --> TicketControl: Error message
TicketControl --> GUI: Error message
GUI --> User: Could not withdraw payment




@enduml