@startuml

(*)  --> "Login"
If "" then
--> [Failed] "Try again"
--> "Login"
else
--> [Success]"Make Event"
Endif
--> "Add location"
--> "Add description to event"
--> "Add age restriction"
--> "Add price to event"
--> "Add time and date"
--> "Add capacity"
--> "Publish event"
-->(*)

@enduml