@startuml
(*)  --> "Velg Event"
If "Er det ledig plass" then
--> [Ja] "Vis ledige plasser"
--> "Bruker velger plass"
--> "Be om betalingskort"
If "Autentiser kort" then
--> [Autentisert] "Transaksjon fullført"
else
--> [Ikke autentisert] "Transaksjon stoppet"
Endif
else
--> [Nei] "Ingen ledige plasser"
Endif
@enduml